### ISSUE TITLE
Missing dependency to playcanvas.Vec2

### ISSUE THREAD

**Issue by Reeley** [playcanvas/pcui-graph#8]
I've tried to get the library to run for quite some time now.

I was successful at building and adding it to my html page via a script tag.

This is the error i get, when trying to create a new Graph:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'Vec2')
    at new JointGraph (pcui-graph.js:40913)
    at new GraphView (pcui-graph.js:44975)
    at Graph._buildGraphFromData (pcui-graph.js:45567)
    at new Graph (pcui-graph.js:45543)
    at (index):63
```

On further inspection it looks like the library is referering to the class ``playcanvas.Vec2`` which is not included in the library itself.

I guess this is the class Vec2 from the ``playcanvas/engine`` project?

**Comment by willeastcott** [comment]
Yeah, IMHO, PCUI-Graph shouldn't have a dependency on the PlayCanvas Engine. @ellthompson and I have already had a chat about this. We'll resolve it when we have a moment.
